"""store company intelligence evidence

Revision ID: 343f6b758676
Revises: ff2c882eebe3
Create Date: 2026-08-25 18:14:02.762070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '343f6b758676'
down_revision: Union[str, Sequence[str], None] = 'ff2c882eebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_evidence',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'evidence_id')
    )
    op.add_column('companies', sa.Column('information', sa.JSON(), nullable=False))
    op.add_column('jobs', sa.Column('role_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'role_summary')
    op.drop_column('companies', 'information')
    op.drop_table('company_evidence')
    # ### end Alembic commands ###
