"""persist requirement match classifications

Revision ID: 4a4c0631f170
Revises: 915bfe07d101
Create Date: 2026-08-25 17:29:36.983311
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4a4c0631f170'
down_revision: Union[str, Sequence[str], None] = '915bfe07d101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requirement_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_requirement_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'NOT_SUPPORTED', 'UNKNOWN', name='requirementmatchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_requirement_id', 'candidate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requirement_matches')
    # ### end Alembic commands ###
