"""store job analysis metadata

Revision ID: ff2c882eebe3
Revises: 6f5c2d9b4e11
Create Date: 2026-08-25 18:03:58.449938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ff2c882eebe3'
down_revision: Union[str, Sequence[str], None] = '6f5c2d9b4e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('posting_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('application_method', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_method')
    op.drop_column('jobs', 'posting_time')
    op.drop_column('jobs', 'experience_level')
    # ### end Alembic commands ###
